version: "3.1"
networks:
  my-network:
    driver: bridge
services:
  flask:
    build: ./flask_app
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - my-network
  django:
    build: ./django_app
    container_name: django-app
    ports:
      - "8000:8000"
    networks:
      - my-network    
  nginx:
      build: ./nginx
      container_name: webserver
      ports:
        - "80:80"
      networks:
        - my-network
      depends_on:
        - flask
        - django
